:concurrency: 5
:max_retries: 5
staging:
  :concurrency: 5
production:
  :concurrency: 5
:queues:
  - default
  - mailers
:schedule:
  email_hello:           
    every: 2.days      
    class: EmailHelloJob